// Generates one module per icon under src/icons/ from a Material Symbols
// dump (historically src/components/icons.tsx, now snapshots/icons-source.tsx
// passed as argv[2]). Per-icon modules with named exports are what make the
// set tree-shakable — a single `Icons` object cannot be dead-code-eliminated,
// so every consumer used to bundle all ~3900 icons (~3 MB).
//
// Output is committed to git (like the registry JSON) and excluded from
// prettier/eslint — regenerate with `node scripts/generate-icons.mjs <dump>`.

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { join } from 'node:path'

const [sourcePath] = process.argv.slice(2)
if (!sourcePath || !existsSync(sourcePath)) {
  console.error(
    'Usage: node scripts/generate-icons.mjs <icons-dump.tsx>\n' +
      'The dump must contain `key: (props: IconProps) => (<svg…/>),` entries.'
  )
  process.exit(1)
}

const outDir = 'src/icons'
const source = readFileSync(sourcePath, 'utf8')

const ENTRY_RE =
  /^ {2}(\w+): \(props: IconProps\) => \(\n([\s\S]*?)\n {2}\),$/gm

const BANNER = '// Generated by scripts/generate-icons.mjs — do not edit.\n'

function exportName(key) {
  return (
    'Icon' +
    key
      .replace(/^_/, '')
      .split('_')
      .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
      .join('')
  )
}

function fileBase(key) {
  return key.replace(/^_/, '').replace(/_/g, '-')
}

const icons = []
for (const [, key, body] of source.matchAll(ENTRY_RE)) {
  icons.push({ key, body })
}

if (icons.length === 0) {
  console.error(`No icon entries found in ${sourcePath}`)
  process.exit(1)
}

// Guard against name/file collisions before writing anything.
const seenNames = new Map()
const seenFiles = new Map()
for (const icon of icons) {
  const name = exportName(icon.key)
  const file = fileBase(icon.key)
  if (seenNames.has(name)) {
    throw new Error(
      `Export name collision: ${name} (${seenNames.get(name)} vs ${icon.key})`
    )
  }
  if (seenFiles.has(file)) {
    throw new Error(
      `File name collision: ${file} (${seenFiles.get(file)} vs ${icon.key})`
    )
  }
  seenNames.set(name, icon.key)
  seenFiles.set(file, icon.key)
}

// Clean regenerate: remove stale modules, keep nothing handwritten here.
if (existsSync(outDir)) {
  for (const existing of readdirSync(outDir)) {
    rmSync(join(outDir, existing))
  }
}
mkdirSync(outDir, { recursive: true })

writeFileSync(
  join(outDir, 'types.ts'),
  `${BANNER}import type { SVGProps } from 'react'

export type IconProps = SVGProps<SVGSVGElement>
`
)

const indexLines = []
for (const icon of icons) {
  const name = exportName(icon.key)
  const file = fileBase(icon.key)
  writeFileSync(
    join(outDir, `${file}.tsx`),
    `${BANNER}import type { IconProps } from './types.js'

export function ${name}(props: IconProps) {
  return (
${icon.body}
  )
}
`
  )
  indexLines.push(`export * from './${file}.js'`)
}

writeFileSync(
  join(outDir, 'index.ts'),
  `${BANNER}export type { IconProps } from './types.js'
${indexLines.sort().join('\n')}
`
)

console.log(`✔ Generated ${icons.length} icon modules in ${outDir}/`)
