// Icon module generator/maintainer for src/icons/.
//
// Per-icon modules with named exports are what make the set tree-shakable —
// a single `Icons` object cannot be dead-code-eliminated, so every consumer
// used to bundle all ~3900 icons (~3 MB). Output is committed to git (like
// the registry JSON) and excluded from prettier/eslint.
//
// Usage:
//   node scripts/generate-icons.mjs regenerate <dump.tsx>
//       Full regeneration from a Material Symbols dump containing
//       `key: (props: IconProps) => (<svg…/>),` entries (the pre-v2
//       components/icons.tsx format).
//   node scripts/generate-icons.mjs add <snake_case_name> <icon.svg>
//       Add (or update) a single icon from an SVG file. Extracts the
//       viewBox and the `d` of each <path>; other SVG features are not
//       supported — keep source icons path-only, like Material Symbols.
//   node scripts/generate-icons.mjs index
//       Rewrite src/icons/index.ts from the directory listing.
//   node scripts/generate-icons.mjs check
//       Verify directory ↔ index parity and module shape (run in CI).

import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const outDir = 'src/icons'
const BANNER = '// Generated by scripts/generate-icons.mjs — do not edit.\n'
const ENTRY_RE = /^ {2}(\w+): \(props: IconProps\) => \(\n([\s\S]*?)\n {2}\),$/gm

function exportName(key) {
  return (
    'Icon' +
    key
      .replace(/^_/, '')
      .split(/[_-]/)
      .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
      .join('')
  )
}

function fileBase(key) {
  return key.replace(/^_/, '').replace(/_/g, '-')
}

function iconFiles() {
  return readdirSync(outDir)
    .filter((name) => name.endsWith('.tsx'))
    .map((name) => name.replace(/\.tsx$/, ''))
    .sort()
}

// Canonical generated content for types.ts / index.ts. These are the single
// source of truth shared by the writers (regenerate/index) and check(), so the
// exact-match check can never drift from what the generator actually produces.
function typesContent() {
  return `${BANNER}import type { SVGProps } from 'react'

export type IconProps = SVGProps<SVGSVGElement>
`
}

// `files` defaults to a fresh directory read for the writers (which have just
// mutated src/icons/); check() passes its own snapshot so the canonical barrel
// is built from the same file list its parity checks use — one readdir, no
// chance of the two reasoning about different snapshots.
function indexContent(files = iconFiles()) {
  const lines = files.map((file) => `export * from './${file}.js'`)
  return `${BANNER}export type { IconProps } from './types.js'
${lines.join('\n')}
`
}

function writeTypes() {
  writeFileSync(join(outDir, 'types.ts'), typesContent())
}

function writeIndex() {
  const content = indexContent()
  writeFileSync(join(outDir, 'index.ts'), content)
  return content.match(/^export \* from /gm)?.length ?? 0
}

function writeIconModule(key, body) {
  writeFileSync(
    join(outDir, `${fileBase(key)}.tsx`),
    `${BANNER}import type { IconProps } from './types.js'

export function ${exportName(key)}(props: IconProps) {
  return (
${body}
  )
}
`,
  )
}

function regenerate(sourcePath) {
  if (!sourcePath || !existsSync(sourcePath)) {
    console.error('regenerate: dump file not found:', sourcePath)
    process.exit(1)
  }

  const source = readFileSync(sourcePath, 'utf8')
  const icons = [...source.matchAll(ENTRY_RE)].map(([, key, body]) => ({
    key,
    body,
  }))

  if (icons.length === 0) {
    console.error(`No icon entries found in ${sourcePath}`)
    process.exit(1)
  }

  // Guard against name/file collisions before writing anything.
  const seenNames = new Map()
  for (const icon of icons) {
    const name = exportName(icon.key)
    if (seenNames.has(name)) {
      throw new Error(`Export name collision: ${name} (${seenNames.get(name)} vs ${icon.key})`)
    }
    seenNames.set(name, icon.key)
  }

  if (existsSync(outDir)) {
    for (const existing of readdirSync(outDir)) {
      rmSync(join(outDir, existing))
    }
  }
  mkdirSync(outDir, { recursive: true })

  writeTypes()
  for (const icon of icons) {
    writeIconModule(icon.key, icon.body)
  }
  const count = writeIndex()
  console.log(`✔ Regenerated ${count} icon modules in ${outDir}/`)
}

function add(key, svgPath) {
  if (!key || !/^[a-z][a-z0-9_]*$/.test(key)) {
    console.error('add: name must be snake_case (e.g. arrow_forward)')
    process.exit(1)
  }
  if (!svgPath || !existsSync(svgPath)) {
    console.error('add: svg file not found:', svgPath)
    process.exit(1)
  }

  const svg = readFileSync(svgPath, 'utf8')
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1]
  const paths = [...svg.matchAll(/<path[^>]*?\bd="([^"]+)"[^>]*?\/?>/g)].map(([, d]) => d)

  if (!viewBox || paths.length === 0) {
    console.error('add: svg must contain a viewBox and at least one <path d>')
    process.exit(1)
  }

  const pathLines = paths.map((d) => `      <path d="${d}" />`).join('\n')
  const body = `    <svg
      fill="currentColor"
      data-slot="icon"
      viewBox="${viewBox}"
      {...props}
    >
${pathLines}
    </svg>`

  writeIconModule(key, body)
  writeIndex()
  console.log(`✔ Wrote ${outDir}/${fileBase(key)}.tsx (${exportName(key)})`)
}

function readOrEmpty(name) {
  const path = join(outDir, name)
  return existsSync(path) ? readFileSync(path, 'utf8') : ''
}

function check() {
  const problems = []

  if (!existsSync(join(outDir, 'types.ts'))) {
    problems.push('missing src/icons/types.ts')
  } else if (readOrEmpty('types.ts') !== typesContent()) {
    problems.push('src/icons/types.ts drifted from generated form')
  }

  const files = iconFiles()
  const index = readOrEmpty('index.ts')

  // Exact-match against the canonical barrel. The parity checks below are
  // order-INDEPENDENT (Set membership), so on their own they miss a reordered
  // index.ts or a relocated IconProps export — the silent "Sort Lines" drift.
  // This byte comparison is what catches export order, IconProps placement,
  // banner, and trailing-newline drift.
  if (index !== indexContent(files)) {
    problems.push(
      'src/icons/index.ts is not in canonical generated form (export order, IconProps placement, or banner drift)',
    )
  }

  const indexed = new Set(
    [...index.matchAll(/^export \* from '\.\/(.+)\.js'$/gm)].map(([, f]) => f),
  )

  for (const file of files) {
    if (!indexed.has(file)) {
      problems.push(`src/icons/${file}.tsx is not exported from index.ts`)
    }
    const source = readFileSync(join(outDir, `${file}.tsx`), 'utf8')
    const expected = exportName(file)
    if (!source.includes(`export function ${expected}(`)) {
      problems.push(`src/icons/${file}.tsx does not export ${expected} (file/export mismatch)`)
    }
  }
  for (const file of indexed) {
    if (!files.includes(file)) {
      problems.push(`index.ts exports './${file}.js' but the file is missing`)
    }
  }

  if (problems.length > 0) {
    console.error('Icon module drift detected:\n')
    for (const problem of problems) {
      console.error(`  - ${problem}`)
    }
    console.error(
      "\nRun 'node scripts/generate-icons.mjs index' to rebuild the barrel, or fix the listed modules.",
    )
    process.exit(1)
  }

  console.log(`✔ ${files.length} icon modules consistent with index.ts`)
}

const [command, ...args] = process.argv.slice(2)

switch (command) {
  case 'regenerate':
    regenerate(args[0])
    break
  case 'add':
    add(args[0], args[1])
    break
  case 'index':
    writeTypes()
    console.log(`✔ Rebuilt index with ${writeIndex()} icon modules`)
    break
  case 'check':
    check()
    break
  default:
    console.error('Usage: generate-icons.mjs <regenerate <dump>|add <name> <svg>|index|check>')
    process.exit(1)
}
