// Generated by scripts/generate-icons.mjs — do not edit.
import type { IconProps } from './types.js'

export function IconCheckIndeterminateSmall(props: IconProps) {
  return (
    <svg
      fill="currentColor"
      data-slot="icon"
      viewBox="0 -960 960 960"
      {...props}
    >
      <path d="M280-440q-17 0-28.5-11.5T240-480q0-17 11.5-28.5T280-520h400q17 0 28.5 11.5T720-480q0 17-11.5 28.5T680-440H280Z" />
    </svg>
  )
}
