// Generated by scripts/generate-icons.mjs — do not edit.
import type { IconProps } from './types.js'

export function IconChromeMinimize(props: IconProps) {
  return (
    <svg fill="currentColor" data-slot="icon" viewBox="0 96 960 960" {...props}>
      <path d="M200 896q-17 0-28.5-11.5T160 856q0-17 11.5-28.5T200 816h560q17 0 28.5 11.5T800 856q0 17-11.5 28.5T760 896H200Z" />
    </svg>
  )
}
