// Generated by scripts/generate-icons.mjs — do not edit.
import type { IconProps } from './types.js'

export function IconCrop916(props: IconProps) {
  return (
    <svg
      fill="currentColor"
      data-slot="icon"
      viewBox="0 -960 960 960"
      {...props}
    >
      <path d="M360-120q-33 0-56.5-23.5T280-200v-560q0-33 23.5-56.5T360-840h240q33 0 56.5 23.5T680-760v560q0 33-23.5 56.5T600-120H360Zm0-640v560h240v-560H360Zm0 0v560-560Z" />
    </svg>
  )
}
