// Generated by scripts/generate-icons.mjs — do not edit.
import type { IconProps } from './types.js'

export function IconGoToLine(props: IconProps) {
  return (
    <svg
      fill="currentColor"
      data-slot="icon"
      viewBox="0 -960 960 960"
      {...props}
    >
      <path d="M480-680q-25 0-42.5-17.5T420-740q0-25 17.5-42.5T480-800q25 0 42.5 17.5T540-740q0 25-17.5 42.5T480-680Zm0 520q-25 0-42.5-17.5T420-220q0-25 17.5-42.5T480-280q25 0 42.5 17.5T540-220q0 25-17.5 42.5T480-160Z" />
    </svg>
  )
}
