// Generated by scripts/generate-icons.mjs — do not edit.
import type { IconProps } from './types.js'

export function IconLineEnd(props: IconProps) {
  return (
    <svg
      fill="currentColor"
      data-slot="icon"
      viewBox="0 -960 960 960"
      {...props}
    >
      <path d="M780-380q-31 0-56-17t-36-43H120q-17 0-28.5-11.5T80-480q0-17 11.5-28.5T120-520h568q11-26 36-43t56-17q42 0 71 29t29 71q0 42-29 71t-71 29Z" />
    </svg>
  )
}
