// Generated by scripts/generate-icons.mjs — do not edit.
import type { IconProps } from './types.js'

export function IconLocationAutomation(props: IconProps) {
  return (
    <svg fill="currentColor" data-slot="icon" viewBox="0 0 24 24" {...props}>
      <path d="M4 19V7l8-6 8 6v4h-2V8l-6-4.5L6 8v9h6v2Zm14.5 3-1.4-3.1-3.1-1.4 3.1-1.4 1.4-3.1 1.4 3.1 3.1 1.4-3.1 1.4Z" />
    </svg>
  )
}
