// Generated by scripts/generate-icons.mjs — do not edit.
import type { IconProps } from './types.js'

export function IconRMobiledata(props: IconProps) {
  return (
    <svg
      fill="currentColor"
      data-slot="icon"
      viewBox="0 -960 960 960"
      {...props}
    >
      <path d="M160-666v66q0 17-11.5 28.5T120-560q-17 0-28.5-11.5T80-600v-240q0-17 11.5-28.5T120-880h160q33 0 56.5 23.5T360-800v54q0 24-14 43.5T312-672l26 61q8 18-3 34.5T304-560q-11 0-20-6t-14-16l-36-84h-74Zm0-80h120v-54H160v54Z" />
    </svg>
  )
}
