// Generated by scripts/generate-icons.mjs — do not edit.
import type { IconProps } from './types.js'

export function IconStop(props: IconProps) {
  return (
    <svg
      fill="currentColor"
      data-slot="icon"
      viewBox="0 -960 960 960"
      {...props}
    >
      <path d="M240-320v-320q0-33 23.5-56.5T320-720h320q33 0 56.5 23.5T720-640v320q0 33-23.5 56.5T640-240H320q-33 0-56.5-23.5T240-320Zm80 0h320v-320H320v320Zm160-160Z" />
    </svg>
  )
}
