import { config } from '@workspace/eslint-config/react-internal'

/** @type {import("eslint").Linter.Config} */
export default [
  ...config,
  {
    // Generated by scripts/generate-icons.mjs (committed like registry
    // output) — ~3900 mechanical modules; linting them adds minutes for
    // zero signal.
    ignores: ['src/icons/**'],
  },
  {
    // Enforce relative imports inside the package source.
    // - "@/*" silently misresolves when apps/web's transpilePackages compiles
    //   our src against its own "@/* → ./*" alias (wrong files, no error).
    // - "@nswds/ui/*" self-imports leak into registry JSON output and trip
    //   the guard in scripts/rewrite-registry-aliases.mjs.
    // shadcn add writes files with "@/..." imports; convert them to relative
    // paths as part of the Radix → Base UI cleanup step.
    files: ['src/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@/*'],
              message:
                "Use a relative import inside packages/ui/src — @/* won't resolve when apps/web transpiles this file.",
            },
            {
              group: ['@nswds/ui/*'],
              message:
                'Use a relative import inside packages/ui/src — self-imports leak into registry output.',
            },
          ],
        },
      ],
    },
  },
  {
    // Single source of truth: components must reference @nswds/tokens tokens, never
    // hardcode colour values. The token layers (colour, radius, space, type, motion)
    // are wired into Tailwind via theme.css, so every visual property has a token-backed
    // utility — there's no reason to inline a raw colour. See AGENTS.md §3 / §8.
    files: ['src/components/**/*.tsx'],
    ignores: ['src/components/**/*.stories.tsx'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector:
            'Literal[value=/#[0-9a-fA-F]{3,8}\\b|\\boklch\\(|\\brgba?\\(|\\bhsla?\\(/]',
          message:
            'No hardcoded colour values in components — reference a semantic token instead (e.g. bg-primary, text-foreground, var(--color-danger-600)). See AGENTS.md §3.',
        },
      ],
    },
  },
]
